pengadaan_barang/Models/Divisi.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Client.Models
{
    public partial class Divisi
    {
        public Divisi()
        {
            Pengadaan = new HashSet<Pengadaan>();
        }

        public int Id { get; set; }
        public string Nama { get; set; }
        public int AnggaraanTetap { get; set; }


        public virtual ICollection<Pengadaan> Pengadaan { get; set; }
    }
}

pengadaan_barang/Models/Satuan.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Client.Models
{
    public  class Satuan
    {
      

        public int Id { get; set; }
        public string Nama { get; set; }

    }
}

pengadaan_barang/Models/Supplier.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Client.Models
{
    public  class Supplier
    {
        
        public int Id { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public string Kota { get; set; }
        public string Email { get; set; }
        public  int Telepon { get; set; }

     
    }
}

pengadaan_barang/Controllers/KabagController.cs
using Client.Models;
using Client.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;

namespace Client.Controllers
{
    public class KabagController : Controller
    {
        DTSMiniProjectContext myContext;

        public KabagController(DTSMiniProjectContext myContext)
        {
            this.myContext = myContext;
        }


        // GET: KabagController -- ALL data Pengajuan Pengadaan
        public ActionResult Index()
        {
            var role = HttpContext.Session.GetString("Role");
            if (role != null)
            {
                if (role.Equals("Kepala Bagian Produksi"))
                {
                    var data = myContext.Pengadaan.Include(x => x.IdSupplierNavigation).
                        Include(y => y.IdBarangNavigation).
                        Include(z => z.IdStatusNavigation).
                        Include(p => p.IdDivisiNavigation)
                        .ToList();

                    return View(data);
                }
            }
            return RedirectToAction("Unauthorized", "ErrorPage");
        }
        // GET: KabagController/CreateSPB 
        public ActionResult CreateSPB()
        {
            ViewModel vm = new ViewModel();
            List<SelectListItem> Product = myContext.Product
                .OrderBy(n => n.NamaProduk)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.NamaProduk.ToString()
                }).ToList();
            vm.Produck = Product;
            List<SelectListItem> Supplier = myContext.Supplier
                .OrderBy(n => n.Nama)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Nama.ToString()
                }).ToList();
            vm.Supplier = Supplier;
                List<SelectListItem> Divisi = myContext.Divisi
                .OrderBy(n => n.Nama)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Nama.ToString()
                }).ToList();
            vm.Divisi = Divisi;
            return View(vm);
        }

        // POST: KabagController/CreateSPB
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSPB(Pengadaan pengadaan)
        {
            if (ModelState.IsValid)
            {
                myContext.Pengadaan.Add(pengadaan);
                var result = myContext.SaveChanges();
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return View();

        }
        // GET: KabagController/DeleteSPB

        [HttpGet("Kabag/DeleteSPB/{id:int}")]
        public IActionResult DeleteSPB(int id)
        {
            var pengadaan = myContext.Pengadaan.Where(a => a.Id == id).FirstOrDefault();
            myContext.Pengadaan.Remove(pengadaan);
            myContext.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET: KabagController/EditSPB
        [HttpGet("Kabag/EditSPB/{id:int}")]
        public IActionResult EditSPB(int id)
        {
            ViewModel viewModel = new ViewModel();
            viewModel.pengadaan = myContext.Pengadaan.Where(a => a.Id == id).FirstOrDefault();

            List<SelectListItem> product = myContext.Product
                .OrderBy(n => n.NamaProduk)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.NamaProduk
                }).ToList();
            viewModel.Produck = product;

            List<SelectListItem> supplier = myContext.Supplier
                .OrderBy(n => n.Nama)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Nama
                }).ToList();
            viewModel.Supplier = supplier;

            return View(viewModel);
        }
        //POST: KabagController/EditSPB
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSPB(int id, Pengadaan pengadaan)
        {
            if (ModelState.IsValid)
            {
                var data = myContext.Pengadaan.Where(a => a.Id == id).FirstOrDefault();
                
            if (data != null)
                {
                    data.IdSupplier = pengadaan.IdSupplier;
                    data.Kuantitas = pengadaan.Kuantitas;
                }
                myContext.Pengadaan.Update(data);
                var result = myContext.SaveChanges();
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return View();
        }




        //----------------------=================== Barang =========================-------------------------------------
        // GET: KabagController
        public ActionResult Barang()
        {
            var data = myContext.Product.Include(x => x.IdSupplierNavigation).Include(y => y.IdSatuanNavigation).ToList();
           
            return View(data);
        }
        // GET: KabagController/CreateBarang
        public ActionResult CreateBarang()
        {
            ViewModel viewModel = new ViewModel();

            //List<SelectListItem> supplier = myContext.Supplier
            //    .OrderBy(n => n.Nama)
            //    .Select(n => new SelectListItem
            //    {
            //        Value = n.Id.ToString(),
            //        Text = n.Nama
            //    }).ToList();
            //viewModel.Supplier = supplier;

            List<SelectListItem> satuan = myContext.Satuan
                .OrderBy(n => n.Nama)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Nama
                }).ToList();
            viewModel.Satuan = satuan;
            return View(viewModel);
        }

        // POST: KabagController/CreateBarang
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBarang(Product product)
        {
            if (ModelState.IsValid)
            {
                myContext.Product.Add(product);
                var result = myContext.SaveChanges();
                if (result > 0)
                    return RedirectToAction("Barang");
            }
            return View();
            
        }

        //GET : KabagController/EditBarang/id
        [HttpGet("Kabag/EditBarang/{id:int}")]
        public IActionResult EditBarang(int id)
        {
            ViewModel viewModel = new ViewModel();
            viewModel.product = myContext.Product.Where(a => a.Id == id).FirstOrDefault();

            List<SelectListItem> satuan = myContext.Satuan
                .OrderBy(n => n.Nama)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Nama
                }).ToList();
            viewModel.Satuan = satuan;

            List<SelectListItem> supplier = myContext.Supplier
                .OrderBy(n => n.Nama)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Nama
                }).ToList();
            viewModel.Supplier = supplier;

            return View(viewModel);
        }

        //POST : KabagController/EditBarang/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditBarang(int id, Product product)
        {
            if (ModelState.IsValid)
            {
                var data = myContext.Product.Where(a => a.Id == id).FirstOrDefault();

                if (data != null)
                {
                    data.NamaProduk = product.NamaProduk;
                    data.StockProduct = product.StockProduct;
                    data.IdSatuan = product.IdSatuan;
                    data.HargaProduct = product.HargaProduct;
                    data.IdSupplier = product.IdSupplier;
                }
                myContext.Product.Update(data);
                var result = myContext.SaveChanges();
                if (result > 0)
                    return RedirectToAction("Barang");
            }
            return View();
        }

        // GET: KabagController/DeleteBarang
        [HttpGet("Kabag/DeleteBarang/{id:int}")]
        public IActionResult DeleteBarang(int id)
        {
            var delprod = myContext.Product.Where(a => a.Id == id).FirstOrDefault();
            myContext.Product.Remove(delprod);
            myContext.SaveChanges();
            return RedirectToAction("Barang");
        }


       //---==== Supplier ====---
        // GET: KabagController
        public ActionResult Supplier()
        {
            

            return View();
        }
        // GET: KabagController/CreateSupplier
        public ActionResult CreateSupplier()
        {
            return View();
        }

        // POST: KabagController/CreateSupplier
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSupplier(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                myContext.Supplier.Add(supplier);
                var result = myContext.SaveChanges();
                if (result > 0)
                    return RedirectToAction("Supplier");
            }
            return View();

        }

        //GET :KabagController/EditSupplier/id
        [HttpGet("Kabag/EditSupplier/{id:int}")]
        public IActionResult EditSupplier(int id)
        {
            ViewModel viewModel = new ViewModel();

pengadaan_barang/Views/Kabag/CreateBarang.cshtml
@model Client.ViewModels.ViewModel

@{
    ViewData["Title"] = "Kabag | Tambah Barang";
    Layout = "_LayoutKabag";

}

    @section Sidebar{
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-action="Index">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-boxes"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Pengadaan Barang</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" asp-action="Index">
                <i class="fa fa-home" aria-hidden="true"></i>
                <span>Halaman Utama</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Barang -->
        <li class="nav-item active ">
            <a asp-action="Barang" class="nav-link">
                <<i class="fa fa-archive" aria-hidden="true"></i>
                <span>Barang</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Supplier -->
        <li class="nav-item">
            <a asp-action="Supplier" class="nav-link">
                <i class="fa fa-industry" aria-hidden="true"></i>
                <span>Pemasok</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Satuan -->
        <li class="nav-item">
            <a asp-action="Satuan" class="nav-link">
                <i class="fa fa-hashtag" aria-hidden="true"></i>
                <span>Satuan</span>
            </a>
        </li>
                <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Divisi -->
        <li class="nav-item">
            <a asp-action="Divisi" class="nav-link">
                <i class="fa fa-users" aria-hidden="true"></i>
                <span>Divisi</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        @*<!-- Nav Item - Riwayat -->
        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Riwayat</span>
            </a>
        </li>



        <!-- Divider -->
        <hr class="sidebar-divider">*@


        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tammbah Daftar Barang</h6>
    </div>
    <div class="container mt-4">
        <div class="form">
            <form asp-action="CreateBarang">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="@Model.product.NamaProduk" class="control-label">Nama Produk</label>
                    <input asp-for="@Model.product.NamaProduk" class="form-control" />
                    <span asp-validation-for="@Model.product.NamaProduk" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.product.IdSatuan" class="control-label">Satuan</label>
                    <select asp-for="@Model.product.IdSatuan" class="form-control" asp-items="@Model.Satuan"></select>
                    @*<input asp-for="@Model.product.IdSatuan" class="form-control" />*@
                    <span asp-validation-for="@Model.product.IdSatuan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.product.HargaProduct" class="control-label">Harga Produk</label>
                    <input asp-for="@Model.product.HargaProduct" class="form-control" />
                    <span asp-validation-for="@Model.product.HargaProduct" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.product.StockProduct" class="control-label">Jumlah Persediaan</label>
                    <input asp-for="@Model.product.StockProduct" class="form-control" />
                    <span asp-validation-for="@Model.product.StockProduct" class="text-danger"></span>
                </div>
                @*<div class="form-group">
                    <label asp-for="@Model.product.IdSupplier" class="control-label"></label>
                    <select asp-for="@Model.product.IdSupplier" class="form-control" asp-items="@Model.Supplier"></select>
                    <span asp-validation-for="@Model.product.IdSupplier" class="text-danger"></span>
                </div>*@
               <div class="form-group row">
                    <div class="col">
                        <input type="submit" value="Tambah Data Barang" class="btn btn-success" />
                        <a asp-controller="Kabag" asp-action="barang"> <button type="button" class="btn btn-danger">Batal</button>  </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
    

pengadaan_barang/Views/Kabag/CreateSupplier.cshtml
@model Client.ViewModels.ViewModel

@{
    ViewData["Title"] = "Kabag | Edit Supplier";
    Layout = "_LayoutKabag";

}

    @section Sidebar{
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-action="Index">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-boxes"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Pengadaan Barang</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item  ">
            <a class="nav-link" asp-action="Index">
                <i class="fa fa-home" aria-hidden="true"></i>
                <span>Halaman Utama</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Barang -->
        <li class="nav-item ">
            <a asp-action="Barang" class="nav-link">
                <i class="fa fa-archive" aria-hidden="true"></i>
                <span>Barang</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Supplier -->
        <li class="nav-item active">
            <a asp-action="Supplier" class="nav-link">
                <i class="fa fa-industry" aria-hidden="true"></i>
                <span>Supplier</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Satuan -->
        <li class="nav-item">
            <a asp-action="Satuan" class="nav-link">
                <i class="fa fa-hashtag" aria-hidden="true"></i>
                <span>Satuan</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Divisi -->
        <li class="nav-item">
            <a asp-action="Divisi" class="nav-link">
                <i class="fa fa-users" aria-hidden="true"></i>
                <span>Divisi</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

       @* <!-- Nav Item - Riwayat -->
        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Riwayat</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">*@


        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
}


    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Supplier</h6>
        </div>
        <div class="container mt-4">
            <div class="form">
                <form asp-action="CreateSupplier">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="@Model.supplier.Nama" class="control-label">Nama Supplier</label>
                        <input asp-for="@Model.supplier.Nama" class="form-control" />
                        <span asp-validation-for="@Model.supplier.Nama" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.supplier.Alamat" class="control-label">Alamat Supplier</label>
                        <input asp-for="@Model.supplier.Alamat" class="form-control" />
                        <span asp-validation-for="@Model.supplier.Alamat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.supplier.Kota" class="control-label"></label>
                        <input asp-for="@Model.supplier.Kota" class="form-control" />
                        <span asp-validation-for="@Model.supplier.Kota" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.supplier.Email" class="control-label"></label>
                        <input asp-for="@Model.supplier.Email" class="form-control" />
                        <span asp-validation-for="@Model.supplier.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.supplier.Telepon" class="control-label"></label>
                        <input asp-for="@Model.supplier.Telepon" class="form-control" />
                        <span asp-validation-for="@Model.supplier.Telepon" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <a asp-controller="Kabag" asp-action="Supplier"> <button type="button" class="btn btn-danger">Cancel</button>  </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

pengadaan_barang/Views/Kabag/EditBarang.cshtml
@model Client.ViewModels.ViewModel

@{
    ViewData["Title"] = "Kabag | Edit Barang";
    Layout = "_LayoutKabag";

}

    @section Sidebar{
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-action="Index">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-boxes"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Pengadaan Barang</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" asp-action="Index">
               <i class="fa fa-home" aria-hidden="true"></i>
                <span>Halaman Utama</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Barang -->
        <li class="nav-item active">
            <a asp-action="Barang" class="nav-link">
                <i class="fa fa-archive" aria-hidden="true"></i>
                <span>Barang</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Supplier -->
        <li class="nav-item">
            <a asp-action="Supplier" class="nav-link">
                <i class="fa fa-industry" aria-hidden="true"></i>
                <span>Pemasok</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Satuan -->
        <li class="nav-item">
            <a asp-action="Satuan" class="nav-link">
                <i class="fa fa-hashtag" aria-hidden="true"></i>
                <span>Satuan</span>
            </a>
        </li>
                <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - Daftar Divisi -->
        <li class="nav-item">
            <a asp-action="Divisi" class="nav-link">
                <i class="fa fa-users" aria-hidden="true"></i>
                <span>Divisi</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">
        @*<!-- Nav Item - Riwayat -->
        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Riwayat</span>
            </a>
        </li>



        <!-- Divider -->
        <hr class="sidebar-divider">*@


        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Edit Barang</h6>
    </div>
    <div class="container mt-4">
        <div class="form">
            <form asp-action="EditBarang">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="@Model.product.NamaProduk" class="control-label">Nama Produk</label>
                    <input asp-for="@Model.product.NamaProduk" class="form-control" />
                    <span asp-validation-for="@Model.product.NamaProduk" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.product.IdSatuan" class="control-label">Satuan</label>
                    <select asp-for="@Model.product.IdSatuan" class="form-control" asp-items="@Model.Satuan"></select>
                    <span asp-validation-for="@Model.product.IdSatuan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.product.HargaProduct" class="control-label"></label>
                    <input asp-for="@Model.product.HargaProduct" class="form-control" />
                    <span asp-validation-for="@Model.product.HargaProduct" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.product.StockProduct" class="control-label"></label>
                    <input asp-for="@Model.product.StockProduct" class="form-control" />
                    <span asp-validation-for="@Model.product.StockProduct" class="text-danger"></span>
                </div>
               @* <div class="form-group">
                    <label asp-for="@Model.product.IdSupplier" class="control-label"></label>
                    <select asp-for="@Model.product.IdSupplier" class="form-control" asp-items="@Model.Supplier"></select>
                    <span asp-validation-for="@Model.product.IdSupplier" class="text-danger"></span>
                </div>*@
               
                <div class="form-group row">
                    <div class="col">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <a asp-controller="Kabag" asp-action="barang"> <button type="button" class="btn btn-danger">Cancel</button>  </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
    